# Generated by Django 5.1.5 on 2026-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('verification_code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اعتبار سنجی پیامکی',
                'verbose_name_plural': 'اعتبار سنجی پیامکی',
            },
        ),
    ]
