# Generated by Django 5.1.5 on 2026-05-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_first_name_user_image_user_last_name'),
        ('bookmanager', '0002_alter_comment_user_alter_commentreaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.SmallIntegerField(choices=[(0, 'درصدی'), (1, 'مبلغ ثابت')], verbose_name='نوع تخفیف')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
                ('max_usage', models.PositiveIntegerField(default=1, verbose_name='حداکثر دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('sent', 'ارسال شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='قیمت کل (بدون تخفیف)')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('tracking_code', models.CharField(blank=True, max_length=120, null=True, verbose_name='کد رهگیری پستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.coupon', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='نام محصول (در لحظه خرید)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت واحد (در لحظه خرید)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmanager.book', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی')),
                ('authority', models.CharField(db_index=True, max_length=255, verbose_name='توکن درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری (RefID)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت پرداخت')),
                ('gateway', models.CharField(default='zarinpal', max_length=50, verbose_name='درگاه بانکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع تراکنش')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید نهایی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='account.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
