# Generated by Django 5.1.5 on 2026-05-05 21:49

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام نویسنده')),
                ('english_name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام انگلیسی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/authors', verbose_name='عکس نویسنده')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('writing_field', models.CharField(blank=True, choices=[('philosophical', 'فلسفی'), ('psychological', 'روانشناختی'), ('magical_realism', 'رئالیسم جادویی'), ('crime_mystery', 'معمایی و جنایی'), ('romance_social', 'عاشقانه / اجتماعی'), ('literary_fiction', 'ادبیات داستانی'), ('social_novel', 'رمان اجتماعی'), ('romance', 'رمان عاشقانه'), ('philosophical_novel', 'رمان فلسفی'), ('political_fiction', 'ادبیات سیاسی'), ('historical_fiction', 'داستان تاریخی'), ('realism', 'رئالیسم'), ('social_realism', 'رئالیسم اجتماعی'), ('magic_realism', 'رئالیسم جادویی'), ('modernism', 'مدرنیسم'), ('postmodern', 'پست\u200cمدرنیسم'), ('surreal', 'سوررئال'), ('short_story', 'داستان کوتاه'), ('poetry', 'شعر'), ('modern_poetry', 'شعر معاصر'), ('classic_poetry', 'شعر کلاسیک'), ('fantasy', 'فانتزی'), ('epic_fantasy', 'فانتزی حماسی'), ('sci_fi', 'علمی\u200cتخیلی'), ('adventure', 'ماجراجویی'), ('dystopian', 'دیستوپیا / پادآرمان\u200cشهری'), ('crime', 'جنایی'), ('mystery', 'معمایی'), ('thriller', 'هیجان\u200cانگیز'), ('detective', 'کارآگاهی'), ('philosophy', 'فلسفه'), ('psychology', 'روانشناسی'), ('existential', 'اگزیستانسیالیسم'), ('sociology', 'جامعه\u200cشناسی'), ('children', 'کودک'), ('young_adult', 'نوجوان'), ('journalism', 'روزنامه\u200cنگاری'), ('biography', 'زندگی\u200cنامه'), ('memoir', 'خاطره\u200cنویسی'), ('reportage', 'گزارش\u200cنویسی'), ('mythology', 'اسطوره'), ('religion', 'دین'), ('history', 'تاریخ'), ('war', 'ادبیات جنگ'), ('social_criticism', 'نقد اجتماعی'), ('symbolism', 'سمبولیسم'), ('humanities', 'انسانیات')], max_length=50, null=True, verbose_name='زمینه نویسندگی')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='پیشه')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='ملیت')),
                ('slug', models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, unique=True)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.', 'unique': 'این نام قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام دسته')),
                ('english_name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.', 'unique': 'این نام انگلیسی قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/categories', verbose_name='تصویر دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام ناشر')),
                ('english_name', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام انگلیسی ناشر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/publishers', verbose_name='لوگو ناشر')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, unique=True)),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشران',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=500, verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, error_messages={'blank': 'این فیلد اجباری است.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='عنوان کتاب')),
                ('english_title', models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('translator', models.CharField(blank=True, max_length=50, null=True, verbose_name='مترجم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(default='assets/img/default.jpg', upload_to='img/books/', verbose_name='تصویر کتاب')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/books/', verbose_name='فایل کتاب (برای نسخه دیجیتال)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('discount_price', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('product_type', models.CharField(choices=[('physical', 'فیزیکی'), ('digital', 'دیجیتال')], max_length=20, verbose_name='نوع محصول')),
                ('format', models.CharField(choices=[('paperback', 'شومیز'), ('hardcover', 'جلد سخت'), ('ebook', 'الکترونیکی'), ('audio', 'صوتی')], max_length=20, verbose_name='فرمت کتاب')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='کد محصول (SKU)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='شابک (ISBN)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صفحات')),
                ('language', models.CharField(default='فارسی', max_length=50, verbose_name='زبان')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('sell_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('average_rating', models.FloatField(default=0, verbose_name='میانگین امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookmanager.author', verbose_name='نویسنده')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('categories', models.ManyToManyField(related_name='books', to='bookmanager.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookmanager.publisher', verbose_name='ناشر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bookmanager.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
