# Generated by Django 5.1.5 on 2026-04-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته')),
                ('english_name', models.CharField(max_length=50, verbose_name='نام انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/categories', verbose_name='تصویر دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام ناشر')),
                ('english_name', models.CharField(max_length=150, verbose_name='نام انگلیسی ناشر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/publishers', verbose_name='لوگو ناشر')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشران',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان کتاب')),
                ('english_title', models.CharField(max_length=150, verbose_name='عنوان انگلیسی')),
                ('author', models.CharField(max_length=150, verbose_name='نویسنده')),
                ('translator', models.CharField(blank=True, max_length=150, null=True, verbose_name='مترجم')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('image', models.ImageField(default='assets/img/default.jpg', upload_to='img/books', verbose_name='تصویر کتاب')),
                ('file', models.FileField(default='assets/file/book.pdf', upload_to='file/books', verbose_name='فایل کتاب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('sell_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('categories', models.ManyToManyField(related_name='books', to='bookmanager.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookmanager.publisher', verbose_name='ناشر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookmanager.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
