# Generated by Django 5.1.5 on 2026-04-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام نویسنده')),
                ('english_name', models.CharField(max_length=150, verbose_name='نام انگلیسی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/authors', verbose_name='عکس نویسنده')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookmanager.author', verbose_name='نویسنده'),
        ),
    ]
