# Generated by Django 5.1.5 on 2026-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0002_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دسته'),
        ),
    ]
