# Generated by Django 5.1.5 on 2026-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0003_alter_category_english_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(error_messages={'blank': 'لطفاً نام انگلیسی را وارد کنید.', 'unique': 'این نام انگلیسی قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'blank': 'لطفاً نام را وارد کنید.', 'unique': 'این نام قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, error_messages={'unique': 'این اسلاگ قبلاً ثبت شده است. یک اسلاگ دیگر انتخاب کنید.'}, unique=True),
        ),
    ]
