# Generated by Django 5.1.5 on 2026-04-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0004_alter_author_slug_alter_book_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='english_name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='english_title',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='عنوان کتاب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.', 'unique': 'این نام انگلیسی قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.', 'unique': 'این نام قبلاً ثبت شده است. یک نام دیگر انتخاب کنید.'}, max_length=50, unique=True, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(error_messages={'blank': 'این فیلد اجباری است.'}, on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(error_messages={'blank': 'این فیلد اجباری است.'}, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookmanager.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=500, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='english_name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام انگلیسی ناشر'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(error_messages={'blank': 'این فیلد اجباری است.'}, max_length=150, verbose_name='نام ناشر'),
        ),
    ]
