# Generated by Django 5.1.5 on 2026-04-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0007_rename_author_comment_user_remove_comment_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
    ]
