# Generated by Django 5.1.5 on 2026-04-28 10:02

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0009_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='ملیت'),
        ),
    ]
