# Generated by Django 5.1.5 on 2026-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0010_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(blank=True, choices=[('writer', 'نویسنده'), ('psychologist', 'روانشناس'), ('speaker', 'سخنران'), ('professor', 'استاد دانشگاه'), ('researcher', 'پژوهشگر'), ('entrepreneur', 'کارآفرین')], max_length=50, null=True, verbose_name='پیشه'),
        ),
        migrations.AddField(
            model_name='author',
            name='writing_field',
            field=models.CharField(blank=True, choices=[('psychology', 'روانشناسی'), ('philosophy', 'فلسفه'), ('literature', 'ادبیات'), ('self_help', 'خودسازی'), ('business', 'کسب و کار'), ('history', 'تاریخ'), ('science', 'علم')], max_length=50, null=True, verbose_name='زمینه نویسندگی'),
        ),
    ]
