# Generated by Django 5.1.5 on 2026-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0011_author_profession_author_writing_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پیشه'),
        ),
    ]
