# Generated by Django 5.1.5 on 2026-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0012_alter_author_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='writing_field',
            field=models.CharField(blank=True, choices=[('literary_fiction', 'ادبیات داستانی'), ('poetry', 'شعر'), ('social_realism', 'رئالیسم اجتماعی'), ('philosophical', 'فلسفی'), ('psychological', 'روانشناختی'), ('fantasy', 'فانتزی'), ('sci_fi', 'علمی\u200cتخیلی'), ('magical_realism', 'رئالیسم جادویی'), ('crime_mystery', 'معمایی و جنایی'), ('journalism', 'روزنامه\u200cنگاری'), ('children', 'کودک و نوجوان'), ('war', 'ادبیات جنگ'), ('modernism', 'مدرنیسم'), ('surreal', 'سوررئال / فراواقع\u200cگرایی'), ('romance_social', 'عاشقانه / اجتماعی')], max_length=50, null=True, verbose_name='زمینه نویسندگی'),
        ),
    ]
