# Generated by Django 5.1.5 on 2026-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0013_alter_author_writing_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='writing_field',
            field=models.CharField(blank=True, choices=[('philosophical', 'فلسفی'), ('psychological', 'روانشناختی'), ('magical_realism', 'رئالیسم جادویی'), ('crime_mystery', 'معمایی و جنایی'), ('romance_social', 'عاشقانه / اجتماعی'), ('literary_fiction', 'ادبیات داستانی'), ('social_novel', 'رمان اجتماعی'), ('romance', 'رمان عاشقانه'), ('philosophical_novel', 'رمان فلسفی'), ('political_fiction', 'ادبیات سیاسی'), ('historical_fiction', 'داستان تاریخی'), ('realism', 'رئالیسم'), ('social_realism', 'رئالیسم اجتماعی'), ('magic_realism', 'رئالیسم جادویی'), ('modernism', 'مدرنیسم'), ('postmodern', 'پست\u200cمدرنیسم'), ('surreal', 'سوررئال'), ('short_story', 'داستان کوتاه'), ('poetry', 'شعر'), ('modern_poetry', 'شعر معاصر'), ('classic_poetry', 'شعر کلاسیک'), ('fantasy', 'فانتزی'), ('epic_fantasy', 'فانتزی حماسی'), ('sci_fi', 'علمی\u200cتخیلی'), ('adventure', 'ماجراجویی'), ('dystopian', 'دیستوپیا / پادآرمان\u200cشهری'), ('crime', 'جنایی'), ('mystery', 'معمایی'), ('thriller', 'هیجان\u200cانگیز'), ('detective', 'کارآگاهی'), ('philosophy', 'فلسفه'), ('psychology', 'روانشناسی'), ('existential', 'اگزیستانسیالیسم'), ('sociology', 'جامعه\u200cشناسی'), ('children', 'کودک'), ('young_adult', 'نوجوان'), ('journalism', 'روزنامه\u200cنگاری'), ('biography', 'زندگی\u200cنامه'), ('memoir', 'خاطره\u200cنویسی'), ('reportage', 'گزارش\u200cنویسی'), ('mythology', 'اسطوره'), ('religion', 'دین'), ('history', 'تاریخ'), ('war', 'ادبیات جنگ'), ('social_criticism', 'نقد اجتماعی'), ('symbolism', 'سمبولیسم'), ('humanities', 'انسانیات')], max_length=50, null=True, verbose_name='زمینه نویسندگی'),
        ),
    ]
