# Generated by Django 5.1.5 on 2026-04-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0014_alter_author_writing_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='میانگین امتیاز'),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('paperback', 'شومیز'), ('hardcover', 'جلد سخت'), ('ebook', 'الکترونیکی'), ('audio', 'صوتی')], default=1, max_length=20, verbose_name='فرمت کتاب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='شابک (ISBN)'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='فارسی', max_length=50, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صفحات'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookmanager.author', verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='bookmanager.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود'),
        ),
        migrations.AlterField(
            model_name='book',
            name='product_type',
            field=models.CharField(choices=[('physical', 'فیزیکی'), ('digital', 'دیجیتال')], max_length=20, verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmanager.publisher', verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sku',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد محصول (SKU)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
