# Generated by Django 5.1.5 on 2026-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0015_remove_book_discount_price_book_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.PositiveSmallIntegerField(default=0, max_length=100, verbose_name='درصد تخفیف'),
        ),
    ]
