# Generated by Django 5.1.5 on 2026-04-29 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0016_book_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
    ]
